// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUWWC36PVkdQRDJfvl3g4BqpmGbcOdR-4',
    appId: '1:789910795020:web:1ffa0dadf4e107cdc38f29',
    messagingSenderId: '789910795020',
    projectId: 'todo-4pm',
    authDomain: 'todo-4pm.firebaseapp.com',
    storageBucket: 'todo-4pm.appspot.com',
    measurementId: 'G-XH723RGVGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6R3FpvzyzamvM8Pxad24L-Q2TilujA5w',
    appId: '1:789910795020:android:79edfa19e0ec076ac38f29',
    messagingSenderId: '789910795020',
    projectId: 'todo-4pm',
    storageBucket: 'todo-4pm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACllJ82Bx81zWxl3zC9AQoQfcANp3QLtg',
    appId: '1:789910795020:ios:016f61a9c4297782c38f29',
    messagingSenderId: '789910795020',
    projectId: 'todo-4pm',
    storageBucket: 'todo-4pm.appspot.com',
    iosBundleId: 'com.example.todo4pm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACllJ82Bx81zWxl3zC9AQoQfcANp3QLtg',
    appId: '1:789910795020:ios:016f61a9c4297782c38f29',
    messagingSenderId: '789910795020',
    projectId: 'todo-4pm',
    storageBucket: 'todo-4pm.appspot.com',
    iosBundleId: 'com.example.todo4pm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUWWC36PVkdQRDJfvl3g4BqpmGbcOdR-4',
    appId: '1:789910795020:web:f09f4c1bb3f1f56fc38f29',
    messagingSenderId: '789910795020',
    projectId: 'todo-4pm',
    authDomain: 'todo-4pm.firebaseapp.com',
    storageBucket: 'todo-4pm.appspot.com',
    measurementId: 'G-F1RTW448WN',
  );
}
